### ISSUE TITLE
Swift - RoaringBitmap - Serialize to base64

### ISSUE THREAD

**Issue by lsmilek1** [RoaringBitmap/SwiftRoaring#1]
Hello, I am trying to serialise a bloom filter generated in a roaring bitmap format to a base64 string, so that I can save it in MongoDB. But the function `portableSerialize` is a bit tricky for me.

I am so far just testing how it works and I generate a random bloom filter values that I later try to convert to buffer -> to data -> to base64:

    func generateBloomFilterData(){
        let bitmap = RoaringBitmap()
        for i in 0..<50 { 
            let random = arc4random_uniform(2)
            if random == 0 {
                bitmap.add(UInt32(i))
            } 
        }  
        let count = (Int(bitmap.count) * MemoryLayout<Int8>.size)
        var buffer = [Int8](repeating: 0, count: count)
        _ = bitmap.portableSerialize(buffer: &buffer)
        let uintBuffer = buffer.map { UInt8(bitPattern: $0) }
        let bufferData = Data(uintBuffer)
        let base64String = bufferData()
        print("buffer size: \(buffer.count), \(uintBuffer.count), base64: \(bufferData.base64EncodedString())")
        //-> send base64 string to database
    }

This generates an error: 

> malloc: MallocStackLogging: attempting to release an index out of
> bounds

The console shows: 

> buffer size: 20, 20, base64: OjAAAAEAAAAAABMAEAAAAAMABQA=

Is there a way how to simply generate a base64 string out of the above generated **RoaringBitmap()** ?

**Comment by lemire** [comment]
I would expect something like this...

```swift
        let size = rbm.portableSizeInBytes()
        var buffer = [Int8](repeating: 0, count: size)
        rbm.portableSerialize(buffer: &buffer)
```

Rather you do...

```swift
    let count = (Int(bitmap.count) * MemoryLayout<Int8>.size)
    var buffer = [Int8](repeating: 0, count: count)
    _ = bitmap.portableSerialize(buffer: &buffer)
```

What is the value `count` in this instance?

Then I do not understand these lines...

```
    let uintBuffer = buffer.map { UInt8(bitPattern: $0) }
    let bufferData = Data(uintBuffer)
    let base64String = bufferData()
```


Note that if you want a bitset, you would be better served with something like https://github.com/lemire/SwiftBitset

**Comment by lsmilek1** [comment]
Oh, great! Thank you for the fast response!

The `count` value is in that case `31`

This seems to work well `let size = rbm.portableSizeInBytes()`, printing following with no error:

> buffer size: 78, 78, base64: OjAAAAEAAAAAAB4AEAAAAAAAAgAEAAUACQAKAAwADQAPABAAEQASABQAFQAXABgAGQAcAB0AHwAhACMAJAAmACcAKQAqACsALAAwADEA

the later lines is my improvisation to encode that rbm to a base64String for easy saving to the MongoDB document. I want to use an [ElasticSearch plugin](https://github.com/jrots/skiplist-elastic-plugin) that is accepting base64 representation and is using the java version of RoaringBitmap.

**Comment by lemire** [comment]
Something like the following seems to work...

```Swift
        let size = rbm.portableSizeInBytes()
        var buffer = [Int8](repeating: 0, count: size)
        _ =  rbm.portableSerialize(buffer: &buffer)
        let uint8Buffer = buffer.map { UInt8(bitPattern: $0) }
        let base64Encoded = Data(uint8Buffer).base64EncodedString()
```

I have added a unit test to check that it does work (and reconstruct the original).

I am going to close this issue once I have added the tests.

**Comment by lemire** [comment]
Done. We now have a base64 serialization/deserialization in CI. I also upgraded to the latest CRoaring library.
