### ISSUE TITLE
Confusing semantics of maximum

### ISSUE THREAD

**Issue by adamnemecek** [RoaringBitmap/SwiftRoaring#6]
I'm confused by the intended semantics of max. In the following example, we have two sets, one which contains a zero and one which is empty. However max returns 0 in both cases. How can I distinguish these cases? Am I supposed to be checking if the set is empty?

```swift
func testFirst() {
    // empty
    let a: RoaringBitmap = []
    print("empty")
    for e in a {
        print(e)
    }
    print("a max", a.max())

    // empty
    print("has 0")
    let b: RoaringBitmap = [0]
    for e in b {
        print(e)
    }

    print("b max", b.max())
}
```

**Comment by lemire** [comment]
> Am I supposed to be checking if the set is empty?

Yes. You can call `isEmpty`.

https://github.com/RoaringBitmap/SwiftRoaring/blob/54cb9c5bdc716abb6307b832a5c56fd637826b74/Sources/SwiftRoaring/RoaringBitmap.swift#L898-L905
